# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="gruvbox-dark"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#3C3836,bg:#282828,fg:#D5C4A1,fg+:#D5C4A1,hl:#D79921,hl+:#D79921,pointer:#D79921,marker:#98971A,spinner:#D79921,info:#928374,header:#928374,border:#928374,prompt:#D79921,query:#D5C4A1,disabled:#928374,gutter:#282828,preview-bg:#282828,preview-fg:#D5C4A1,separator:#928374,label:#D79921"
export EZA_COLORS="di=38;2;215;153;33;1:ex=38;2;152;151;26:ln=38;2;104;157;106:fi=0:or=38;2;204;36;29:mi=38;2;204;36;29:da=38;2;146;131;116:sn=38;2;215;153;33:sb=38;2;215;153;33:uu=38;2;146;131;116:un=38;2;146;131;116:gu=38;2;146;131;116:gn=38;2;146;131;116:ga=38;2;152;151;26:gm=38;2;215;153;33:gd=38;2;204;36;29:gv=38;2;215;153;33:gt=38;2;214;93;14:xx=38;2;146;131;116:da=38;2;146;131;116"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;215;153;33m'    # bold (section headers, command names)
export LESS_TERMCAP_us=$'\e[38;2;215;153;33m'    # underline (options, args)
export LESS_TERMCAP_so=$'\e[38;2;215;153;33;7m'  # reverse (search / status line)
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;204;36;29'
