#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#282828"

    # Status bar
    [statusbar-bg]="#3C3836"
    [statusbar-fg]="#D5C4A1"

    # Session (status-left)
    [session-bg]="#D79921"
    [session-fg]="#282828"
    [session-prefix-bg]="#CC241D"
    [session-copy-bg]="#689D6A"
    [session-search-bg]="#D79921"
    [session-command-bg]="#D0521E"

    # Windows
    [window-active-base]="#D79921"
    [window-active-style]="bold"
    [window-inactive-base]="#928374"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#689D6A"

    # Panes
    [pane-border-active]="#D79921"
    [pane-border-inactive]="#928374"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#AA8A56"
    [good-base]="#98971A"
    [info-base]="#689D6A"
    [warning-base]="#D79921"
    [error-base]="#CC241D"
    [disabled-base]="#928374"

    # Messages
    [message-bg]="#3C3836"
    [message-fg]="#D5C4A1"

    # Popup & menu
    [popup-bg]="#3C3836"
    [popup-fg]="#D5C4A1"
    [popup-border]="#D79921"
    [menu-bg]="#3C3836"
    [menu-fg]="#D5C4A1"
    [menu-selected-bg]="#D79921"
    [menu-selected-fg]="#282828"
    [menu-border]="#D79921"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#D65D0E"
    [magenta]="#D0521E"
    [surface]="#3C3836"
)
